#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd "$DIRECTORY" || exit 1

echo "PROJECT IS RUNNING"

# Pass all the arguments provided to the run script to the Python script
python main.py "$@"
